[build]

This tells Netlify to host files directly from the repository root.
publish = "."

[functions]

This specifies the directory where the serverless functions (generate-ai.js) are located.
directory = "functions"
node_bundler = "esbuild"
