# netlify.toml

[build]
# This tells Netlify to host files directly from the repository root.
publish = "."

[functions]
# This specifies where your Netlify serverless functions live.
directory = "functions"
node_bundler = "esbuild"
